
services:
  db:
    build:
      context: .
      dockerfile: app/data/Dockerfile
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: unless-stopped
  bot:
    build:
      context: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GEMINI_API_KEY=${NEURO_API_KEY}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=5432
      - ADMIN_ID=${ADMIN_ID}
      - URL=${URL}
    depends_on:
      - db
      - redis
    restart: unless-stopped
    expose:
      - "8000"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml

    expose:
      - "9090"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
  redis:
    image: redis:7-alpine
    restart: always
    expose:
      - "6379"
  webapp:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GEMINI_API_KEY=${NEURO_API_KEY}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=5432
      - ADMIN_ID=${ADMIN_ID}
      - URL=${URL}

    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data: {}